version: "3.8"
services:
  worker:
    container_name: worker
    build: .
    command: 
      - allora-node
      - --role=worker
      - --peer-db=/data/worker/peer-database
      - --function-db=/data/worker/function-database
      - --runtime-path=/app/runtime
      - --runtime-cli=bls-runtime
      - --workspace=/data/worker/workspace
      - --private-key=/data/worker/key/priv.bin
      - --log-level=debug
      - --port=9011
      - --topic=allora-topic-2-worker
      - --boot-nodes=/ip4/172.19.0.100/tcp/9010/p2p/12D3KooWGnBz8BLq4U7k7ZTa4PKU9QSE37yZ7YHanmV1tLbYQNBE
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file:
      - .env
    depends_on:
      - head
    networks:
      b7s-local:
        aliases:
          - worker
        ipv4_address: 172.19.0.5

  head:
    container_name: head
    image: alloranetwork/allora-inference-base-head:latest
    command: 
      - allora-node
      - --role=head
      - --peer-db=/data/head/peer-database
      - --function-db=/data/head/function-database
      - --runtime-path=/app/runtime
      - --runtime-cli=bls-runtime
      - --workspace=/data/head/workspace
      - --private-key=/data/head/key/priv.bin
      - --log-level=debug
      - --port=9010
      - --rest-api=:6000
    ports:
      - "6000:6000"
    volumes:
      - type: bind
        source: ./data
        target: /data

    networks:
      b7s-local:
        aliases:
          - head
        ipv4_address: 172.19.0.100

networks:
  b7s-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24